/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 91750
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
    
    //to validate details
    public boolean validateDetails(){
        

        
        
        if (txt_Bid.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Book ID");
            return false;
        }
        
        if (txt_Sid.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Student ID");
            return false;
        }
        
        
        
        return true;
    }

    
    
    //to fetch data and display
    public boolean issuedBook(){
        int studentID = Integer.parseInt(txt_Sid.getText());
        int bookID = Integer.parseInt(txt_Bid.getText());
        try {
            Connection con = DBconnection.getConnection();
            String sql = "select * from issued_bookdetails where book_id = ? and student_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, bookID);
            pst.setInt(2, studentID);
            pst.setString(3, "pending");
            ResultSet rs = pst.executeQuery();
            
          if(rs.next()){
              Issue_ID.setText(rs.getString("id"));
              Sname.setText(rs.getString("student_name"));
              Bname.setText(rs.getString("book_name"));
              Date_issue.setText(rs.getString("issue_date"));
              Date_due.setText(rs.getString("due_date"));
              lbl_error.setText("");
          } else {
              lbl_error.setText("     **NO DATA FOUND**");
              Issue_ID.setText("");
              Sname.setText("");
              Bname.setText("");
              Date_issue.setText("");
              Date_due.setText("");
              return false;
          }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return true;
    }
   
    // to update quatity in database
    public boolean updateBookCount(){
        int bookId = Integer.parseInt(txt_Bid.getText());
        try {
            Connection con = DBconnection.getConnection();
            String sql= "update book_details set quantiy = quantiy + 1 where book_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, bookId);
            
            int rowCount = pst.executeUpdate();
            
            if(rowCount>0){
              return true;
            }
        } catch(Exception e){
            e.printStackTrace();
        }
        return false;
    }
    // to change status of book
    public void status(){
         int bookId = Integer.parseInt(txt_Bid.getText());
        try {
            Connection con = DBconnection.getConnection();
            String sql= "update issued_bookdetails set status = ? where book_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,"Returned");
            pst.setInt(2, bookId);
            
            int rowCount = pst.executeUpdate();
            
            if(rowCount>0){
              JOptionPane.showMessageDialog(this, "Book Returned");
            } else{
                JOptionPane.showMessageDialog(this, "Can't Return Book");
            }
        } catch(Exception e){
            e.printStackTrace();
        }
       
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Sname = new javax.swing.JLabel();
        Date_due = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_error = new javax.swing.JLabel();
        Issue_ID = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Bname = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Date_issue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_Bid = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Sid = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rSMaterialButtonCircle4 = new rojerusan.RSMaterialButtonCircle();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_main.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 333, 5));

        Sname.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Sname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 240, 40));

        Date_due.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Date_due.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Date_due, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 250, 40));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Issue ID : -");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel12.setText("   Details");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 330, 100));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Book Name : -");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 150, 40));

        lbl_error.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbl_error.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(lbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 390, 50));

        Issue_ID.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Issue_ID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Issue_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 240, 40));

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Issue Date : -");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 130, 40));

        Bname.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Bname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 250, 40));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Due Date : -");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 120, 40));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Student Name : -");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 170, 40));

        Date_issue.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Date_issue.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Date_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 250, 40));

        jPanel_main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 450, 830));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel1.setText("    Return Book");
        jPanel_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, 310, 100));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel_main.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1113, 220, 360, 5));

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        jPanel_main.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 0, 50, 70));

        txt_Bid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_Bid.setPlaceholder("Enter Book ID....");
        txt_Bid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_BidFocusLost(evt);
            }
        });
        jPanel_main.add(txt_Bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 300, 250, 40));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Enter Book ID : -");
        jPanel_main.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 300, 150, 40));

        txt_Sid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_Sid.setPlaceholder("Enter Student ID....");
        txt_Sid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_SidFocusLost(evt);
            }
        });
        jPanel_main.add(txt_Sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 370, 250, 40));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Enter Student ID : -");
        jPanel_main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 370, 170, 40));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(102, 102, 255));
        rSMaterialButtonCircle3.setText("FIND");
        rSMaterialButtonCircle3.setFont(new java.awt.Font("Roboto Medium", 0, 22)); // NOI18N
        rSMaterialButtonCircle3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle3MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanel_main.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 550, 340, 80));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel4.setText("Back");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        jPanel_main.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        rSMaterialButtonCircle4.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle4.setText("RETURN");
        rSMaterialButtonCircle4.setFont(new java.awt.Font("Roboto Medium", 0, 22)); // NOI18N
        rSMaterialButtonCircle4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle4MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        jPanel_main.add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 640, 340, 80));

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-2.png"))); // NOI18N
        jPanel_main.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, 640, 740));

        getContentPane().add(jPanel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 830));

        setSize(new java.awt.Dimension(1530, 830));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Homepage home = new Homepage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txt_BidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BidFocusLost
      if (txt_Bid.getText().equals("")){
          lbl_error.setText("");
          Issue_ID.setText("");
          Sname.setText("");
          Bname.setText("");
          Date_issue.setText("");
          Date_due.setText("");
      }   
    }//GEN-LAST:event_txt_BidFocusLost

    private void txt_SidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_SidFocusLost
         if (txt_Sid.getText().equals("")){
          lbl_error.setText("");
          Issue_ID.setText("");
          Sname.setText("");
          Bname.setText("");
          Date_issue.setText("");
          Date_due.setText("");
      }        
    }//GEN-LAST:event_txt_SidFocusLost

    private void rSMaterialButtonCircle3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3MouseClicked

    }//GEN-LAST:event_rSMaterialButtonCircle3MouseClicked

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
    if(validateDetails() == true) {
        issuedBook();
    }
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    private void rSMaterialButtonCircle4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle4MouseClicked

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
       if(issuedBook() == true){
           if(updateBookCount()== true){
               status();
           }
       }
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bname;
    private javax.swing.JLabel Date_due;
    private javax.swing.JLabel Date_issue;
    private javax.swing.JLabel Issue_ID;
    private javax.swing.JLabel Sname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JLabel lbl_error;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private app.bolivia.swing.JCTextField txt_Bid;
    private app.bolivia.swing.JCTextField txt_Sid;
    // End of variables declaration//GEN-END:variables
}
