/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91750
 */
public class viewRecord extends javax.swing.JFrame {

    
    DefaultTableModel model;
    /**
     * Creates new form viewRecord
     */
    public viewRecord() {
        initComponents();
        setBookDetails();
    }
    
      public void setBookDetails(){
       try {
           Connection con = DBconnection.getConnection();
           String sql = "select * from issued_bookdetails";
           PreparedStatement pst = con.prepareStatement(sql);
           ResultSet rs = pst.executeQuery();
            
           while(rs.next()){
               int issueId = rs.getInt("id");
               String bookid = rs.getString("book_id");
               String bookname = rs.getString("book_name");
               String studentId = rs.getString("student_id");
               String studentName = rs.getString("student_name");
               String issueDate = rs.getString("issue_date");
               String dueDate = rs.getString("due_date");
               String status = rs.getString("status");
               
               Object[] obj ={issueId,bookid,bookname,studentId,studentName,issueDate,dueDate,status};
               model = (DefaultTableModel) table_Details.getModel();
               model.addRow(obj);DefaultTableModel model;
               
               
           }
       }catch(Exception e){
                   e.printStackTrace();
                }          
      }
       
      //to fetch data according to date
      public void dataViaDate(){
        
        DefaultTableModel model = (DefaultTableModel) table_Details.getModel();
        model.setRowCount(0);
        
        Date udueDate = Date_due.getDatoFecha();
        Long L2 = udueDate.getTime();
        java.sql.Date sDueDate = new java.sql.Date(L2);
        
        Date uissueDate = Date_issue.getDatoFecha();
        Long L1 = uissueDate.getTime();
        java.sql.Date sIssueDate = new java.sql.Date(L1);
        
        
        
           try {
               
            Connection con = DBconnection.getConnection();
            String sql = "select * from issued_bookdetails where issue_date=? and due_date=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setDate(1, sIssueDate );
            pst.setDate(2, sDueDate);
            ResultSet rs = pst.executeQuery();
            
           if(rs.next()){
               int issueId = rs.getInt("id");
               String bookid = rs.getString("book_id");
               String bookname = rs.getString("book_name");
               String studentId = rs.getString("student_id");
               String studentName = rs.getString("student_name");
               String issueDate = rs.getString("issue_date");
               String dueDate = rs.getString("due_date");
               String status = rs.getString("status");
               
               Object[] obj ={issueId,bookid,bookname,studentId,studentName,issueDate,dueDate,status};
               model = (DefaultTableModel) table_Details.getModel();
               model.addRow(obj);
              
               
               
           } else{
               JOptionPane.showMessageDialog(this, "No Data Found");
               
           }
       }catch(Exception e){
                   e.printStackTrace();
                } 
      }
              

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Date_issue = new rojeru_san.componentes.RSDateChooser();
        jLabel7 = new javax.swing.JLabel();
        Date_due = new rojeru_san.componentes.RSDateChooser();
        jLabel10 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_Details = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 410, 5));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel12.setText("   View All Record");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 380, 100));

        Date_issue.setForeground(new java.awt.Color(255, 51, 51));
        Date_issue.setColorBackground(new java.awt.Color(255, 51, 51));
        Date_issue.setColorForeground(new java.awt.Color(0, 0, 0));
        Date_issue.setPlaceholder("Select Issue Date...  ");
        jPanel1.add(Date_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 330, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Issue Date : -");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 130, 40));

        Date_due.setForeground(new java.awt.Color(255, 255, 255));
        Date_due.setColorBackground(new java.awt.Color(255, 51, 51));
        Date_due.setColorForeground(new java.awt.Color(0, 0, 0));
        Date_due.setPlaceholder("Select Due Date...  ");
        jPanel1.add(Date_due, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 330, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Due Date : -");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 120, 40));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle1.setText("Search");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 220, 190, 60));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel3.setText(" X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 0, 50, 60));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel4.setText("Back");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 120, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-refresh-64.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 330));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_Details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue ID", "Book ID", "Book Name", "Student ID", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        table_Details.setAltoHead(40);
        table_Details.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        table_Details.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        table_Details.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        table_Details.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        table_Details.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        table_Details.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        table_Details.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        table_Details.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_Details.setRowHeight(30);
        table_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DetailsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_Details);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 1400, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1530, 500));

        setSize(new java.awt.Dimension(1530, 830));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DetailsMouseClicked

    }//GEN-LAST:event_table_DetailsMouseClicked

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
       if(Date_due.getDatoFecha()!= null && Date_issue.getDatoFecha()!= null  ){
               dataViaDate();
       } else{
           JOptionPane.showMessageDialog(this, "Please Select Date");
       }
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Homepage home = new Homepage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        DefaultTableModel model = (DefaultTableModel) table_Details.getModel();
        model.setRowCount(0);
        setBookDetails();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser Date_due;
    private rojeru_san.componentes.RSDateChooser Date_issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojeru_san.complementos.RSTableMetro table_Details;
    // End of variables declaration//GEN-END:variables
}
